In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.utils import shuffle

%matplotlib inline

In [3]:
df_train = pd.read_csv('./train.csv')
df_train.head(5)

,ID,Plate,State,License Type,Summons Number,Issue Date,Violation Time,Violation,Judgment Entry Date,Fine Amount,Penalty Amount,Interest Amount,Reduction Amount,Payment Amount,Amount Due,Precinct,County,Issuing Agency,Violation Status
0,24497127,HFP7960,NY,PAS,7070129129,1/22/2017,10:48A,CROSSWALK,NaN,115,0,0.0,0.0,115.0,0.0,44,BX,TRAFFIC,HEARING HELD-GUILTY
1,31015569,85027JW,NY,COM,8424520324,9/30/2016,10:34A,FAIL TO DSPLY MUNI METER RECPT,NaN,65,0,0.0,37.0,28.0,0.0,19,NY,TRAFFIC,HEARING HELD-GUILTY REDUCTION
2,34247801,HHS1694,NY,PAS,8533807454,9/25/2017,09:56A,BIKE LANE,NaN,115,0,0.0,0.0,115.0,0.0,77,K,TRAFFIC,HEARING HELD-GUILTY
3,36714941,2028686,IN,PAS,8477607047,2/15/2017,11:57A,BIKE LANE,NaN,115,0,0.0,115.0,0.0,0.0,14,NY,TRAFFIC,HEARING HELD-NOT GUILTY
4,18489070,HJP7255,NY,PAS,8253044689,9/9/2016,08:49A,NO PARKING-STREET CLEANING,NaN,45,0,0.0,0.0,45.0,0.0,104,Q,TRAFFIC,HEARING PENDING

In [4]:
df_train.tail(5)

,ID,Plate,State,License Type,Summons Number,Issue Date,Violation Time,Violation,Judgment Entry Date,Fine Amount,Penalty Amount,Interest Amount,Reduction Amount,Payment Amount,Amount Due,Precinct,County,Issuing Agency,Violation Status
79995,19425368,ZJZ9356,PA,PAS,8515666339,6/22/2017,08:11A,NO STANDING-DAY/TIME LIMITS,NaN,115,0,0.0,115.0,0.0,0.0,19,NY,TRAFFIC,HEARING HELD-NOT GUILTY
79996,6598339,GTT8769,NY,PAS,8629980291,3/27/2018,10:30A,FAIL TO DSPLY MUNI METER RECPT,NaN,35,0,0.0,35.0,0.0,0.0,114,Q,TRAFFIC,HEARING HELD-NOT GUILTY
79997,33267552,95302MD,NY,COM,8475720183,2/2/2017,04:55P,BIKE LANE,NaN,115,0,0.0,10.0,105.0,0.0,34,NY,TRAFFIC,HEARING HELD-GUILTY REDUCTION
79998,18545959,GRA4102,NY,PAS,8505760396,2/21/2017,12:31P,FAIL TO DSPLY MUNI METER RECPT,NaN,65,0,0.0,65.0,0.0,0.0,9,NY,TRAFFIC,HEARING HELD-NOT GUILTY
79999,27828676,FYD5222,NY,PAS,8170078647,1/6/2017,11:43A,FAIL TO DSPLY MUNI METER RECPT,NaN,35,0,0.0,35.0,0.0,0.0,61,K,TRAFFIC,HEARING HELD-NOT GUILTY

In [5]:
df_train.describe()

,ID,Summons Number,Fine Amount,Penalty Amount,Interest Amount,Reduction Amount,Payment Amount,Amount Due,Precinct
count,8.000000e+04,8.000000e+04,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,1.842031e+07,7.758423e+09,81.649750,7.731687,1.576715,31.322293,49.879611,9.756248,45.762400
std,1.067698e+07,1.942600e+09,34.738941,17.408299,9.609382,41.100653,50.407871,37.456854,39.305557
min,1.350000e+02,1.024252e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.082690e+06,8.064029e+09,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000
50%,1.803750e+07,8.509565e+09,65.000000,0.000000,0.000000,15.000000,40.000000,0.000000,26.000000
75%,2.795702e+07,8.615767e+09,115.000000,0.000000,0.000000,45.000000,95.000000,0.000000,77.000000
max,3.710936e+07,8.745002e+09,515.000000,60.000000,274.910000,545.000000,689.050000,769.910000,472.000000

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 19 columns):
ID                     80000 non-null int64
Plate                  80000 non-null object
State                  80000 non-null object
License Type           80000 non-null object
Summons Number         80000 non-null int64
Issue Date             80000 non-null object
Violation Time         79990 non-null object
Violation              79990 non-null object
Judgment Entry Date    6974 non-null object
Fine Amount            80000 non-null int64
Penalty Amount         80000 non-null int64
Interest Amount        80000 non-null float64
Reduction Amount       80000 non-null float64
Payment Amount         80000 non-null float64
Amount Due             80000 non-null float64
Precinct               80000 non-null int64
County                 79470 non-null object
Issuing Agency         79990 non-null object
Violation Status       80000 non-null object
dtypes: float64(4), int64(5), object(10)
memory usage: 11.6+ MB

In [7]:
df_train['Violation'].unique()

array(['CROSSWALK', 'FAIL TO DSPLY MUNI METER RECPT', 'BIKE LANE',
       'NO PARKING-STREET CLEANING', 'NO STANDING-DAY/TIME LIMITS',
       'EXPIRED MUNI METER', 'DOUBLE PARKING-MIDTOWN COMML',
       'NGHT PKG ON RESID STR-COMM VEH', 'DOUBLE PARKING',
       'OBSTRUCTING DRIVEWAY', 'NO STOPPING-DAY/TIME LIMITS',
       'NO STANDING-BUS STOP', 'FIRE HYDRANT',
       'NO PARKING-DAY/TIME LIMITS', 'FAILURE TO STOP AT RED LIGHT',
       'INSP. STICKER-EXPIRED/MISSING', 'REG. STICKER-EXPIRED/MISSING',
       'PLTFRM LFTS LWRD POS COMM VEH', 'FRONT OR BACK PLATE MISSING',
       'FAIL TO DISP. MUNI METER RECPT', 'SIDEWALK',
       'NO PARKING-EXC. AUTH. VEHICLE', 'OBSTRUCTING TRAFFIC/INTERSECT',
       'PHTO SCHOOL ZN SPEED VIOLATION', 'NO STANDING-EXC. TRUCK LOADING',
       'NO MATCH-PLATE/STICKER', 'EXPIRED MUNI MTR-COMM MTR ZN',
       'NO PARKING-TAXI STAND', 'NO STANDING-COMM METER ZONE',
       'STORAGE-3HR COMMERCIAL', 'NO STANDING-HOTEL LOADING',
       'PARKED BUS-EXC. DESIG. AREA', 'WRONG WAY',
       'NO STANDING-TAXI STAND', 'COMML PLATES-UNALTERED VEHICLE',
       'IDLING', 'NO STANDING-EXC. AUTH. VEHICLE', 'SAFETY ZONE',
       'BUS LANE VIOLATION', 'NO PARKING-EXC. HNDICAP PERMIT',
       "INSP STICKER-MUTILATED/C'FEIT", 'NON-COMPLIANCE W/ POSTED SIGN',
       'NO STANDING EXCP D/S', 'PEDESTRIAN RAMP', 'IMPROPER REGISTRATION',
       'SELLING/OFFERING MCHNDSE-METER', "REG STICKER-MUTILATED/C'FEIT",
       'TRAFFIC LANE', 'NO PARKING-EXC. HOTEL LOADING', 'DETACHED TRAILER',
       'NO STANDING-BUS LANE', 'BEYOND MARKED SPACE',
       'OVERTIME PKG-TIME LIMIT POSTED', 'UNAUTHORIZED PASSENGER PICK-UP',
       'OTHER', 'UNAUTHORIZED BUS LAYOVER',
       'NO STD(EXC TRKS/GMTDST NO-TRK)', 'ANGLE PARKING',
       'NIGHTTIME STD/ PKG IN A PARK', 'TUNNEL/ELEVATED/ROADWAY',
       'MISSING EQUIPMENT', 'EXPIRED METER',
       'FAILURE TO DISPLAY BUS PERMIT', 'OT PARKING-MISSING/BROKEN METR',
       'NO STANDING-FOR HIRE VEH STOP', 'BUS PARKING IN LOWER MANHATTAN',
       nan, 'OVERNIGHT TRACTOR TRAILER PKG',
       'EXCAVATION-VEHICLE OBSTR TRAFF', 'DIVIDED HIGHWAY', 'INTERSECTION',
       'NO STOP/STANDNG EXCEPT PAS P/U', 'NO OPERATOR NAM/ADD/PH DISPLAY',
       'EXPIRED METER-COMM METER ZONE', 'NO STANDING-COMMUTER VAN STOP',
       'WASH/REPAIR VEHCL-REPAIR ONLY', 'PKG IN EXC. OF LIM-COMM MTR ZN',
       'VEHICLE FOR SALE(DEALERS ONLY)', 'ANGLE PARKING-COMM VEHICLE',
       'ELEVATED/DIVIDED HIGHWAY/TUNNL', 'NO STANDING EXCP DP',
       'VACANT LOT'], dtype=object)

In [8]:
df_train['Violation Status'].unique()

array(['HEARING HELD-GUILTY', 'HEARING HELD-GUILTY REDUCTION',
       'HEARING HELD-NOT GUILTY', 'HEARING PENDING', 'ADMIN CLAIM GRANTED',
       'APPEAL REVERSED', 'HEARING ADJOURNMENT', 'APPEAL AFFIRMED',
       'ADMIN CLAIM DENIED', 'ADMIN REDUCTION',
       'HEARING HELD-REINSTATEMENT', 'APPEAL ABANDONED', 'APPEAL MODIFIED',
       'HEARING WAIVED'], dtype=object)

In [28]:
print(df_train['State'].unique())
print(df_train['State'].unique()[0])

['NY' 'IN' 'CT' 'NJ' 'FL' 'TX' 'MA' 'NC' '99' 'VA' 'MN' 'OK' 'IL' 'PA' 'MO'
 'ID' 'MD' 'OH' 'MI' 'WA' 'DP' 'GA' 'OR' 'AZ' 'ME' 'SC' 'IA' 'CA' 'NH' 'TN'
 'DE' 'DC' 'VT' 'ON' 'LA' 'RI' 'AL' 'KY' 'NS' 'NM' 'MT' 'ND' 'PR' 'WI' 'AR'
 'WV' 'QB' 'BC' 'CO' 'NB' 'NV' 'NE' 'MS' 'UT' 'SD' 'KS' 'AB']
NY

In [10]:
df_train['License Type'].unique()

array(['PAS', 'COM', 'CMB', 'OMT', 'PHS', 'APP', 'MOT', 'IRP', 'RGL',
       'MED', 'SEM', '999', 'SRF', 'CHC', 'SCL', 'TRC', 'OMS', 'VAS',
       'ORG', 'SPO', 'PSD', 'OML', 'OMR', 'TRA', 'SRN', 'HIS', 'STA',
       'CMH', 'TRL', 'MCL', 'TOW', 'ITP', 'SPC', 'AGR', 'RGC', 'CSP',
       'DLR', 'AGC', 'LTR', 'OMV', 'CBS', 'ORC', 'NYC', 'HAM', 'LMB',
       'AYG', 'ARG'], dtype=object)

In [11]:
df_train['Precinct'].unique()

array([ 44,  19,  77,  14, 104,  66,  17, 115,  62, 112,  18,  70,  84,
       120,  67,  52,  20, 108,   0,  78,  40, 106,  48,  45,  94, 103,
       114,   9,  46,  28,  90,  68,  13,  61,  43,   5,  10,   1,  73,
       109, 102, 110,  34, 107,  23,   7, 105,  24,  49,  47,  79,  33,
        50,   6,  32,  63,  69,  76,  26,  72,  42,  60,  83,  41,  25,
        30,  88, 122, 111, 101, 100,  75,  71, 121,  81, 113, 123, 401,
        74,  15,  22, 407,  27,   2,  16,  65,  12, 125,   8,  56,  89, 472], dtype=int64)

In [12]:
df_train['County'].unique()

array(['BX', 'NY', 'K', 'Q', 'R', nan, 'ST', 'QN', 'BK', 'MN'], dtype=object)

In [13]:
df_train['Issuing Agency'].unique()

array(['TRAFFIC', 'DEPARTMENT OF SANITATION', 'POLICE DEPARTMENT',
       'DEPARTMENT OF TRANSPORTATION', 'CON RAIL',
       'OTHER/UNKNOWN AGENCIES', 'PARKS DEPARTMENT', 'HOUSING AUTHORITY',
       nan, 'NYS PARKS POLICE', 'NYC TRANSIT AUTHORITY MANAGERS',
       'BOARD OF ESTIMATE', 'PARKING CONTROL UNIT', 'TRANSIT AUTHORITY',
       'NYS COURT OFFICERS'], dtype=object)

In [45]:
df_train_new = df_train[['State', 'License Type', 'Violation', 'Precinct', 'County', 'Issuing Agency', 'Violation Status']]
df_train_new.head()

,State,License Type,Violation,Precinct,County,Issuing Agency,Violation Status
0,NY,PAS,CROSSWALK,44,BX,TRAFFIC,HEARING HELD-GUILTY
1,NY,COM,FAIL TO DSPLY MUNI METER RECPT,19,NY,TRAFFIC,HEARING HELD-GUILTY REDUCTION
2,NY,PAS,BIKE LANE,77,K,TRAFFIC,HEARING HELD-GUILTY
3,IN,PAS,BIKE LANE,14,NY,TRAFFIC,HEARING HELD-NOT GUILTY
4,NY,PAS,NO PARKING-STREET CLEANING,104,Q,TRAFFIC,HEARING PENDING

In [46]:
df_train_new.isnull().sum()

State                 0
License Type          0
Violation            10
Precinct              0
County              530
Issuing Agency       10
Violation Status      0
dtype: int64

In [47]:
df_train_new2 = df_train_new.dropna(axis = 0)
df_train_new2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79469 entries, 0 to 79999
Data columns (total 7 columns):
State               79469 non-null object
License Type        79469 non-null object
Violation           79469 non-null object
Precinct            79469 non-null int64
County              79469 non-null object
Issuing Agency      79469 non-null object
Violation Status    79469 non-null object
dtypes: int64(1), object(6)
memory usage: 4.9+ MB

In [48]:
df_train_new2.head()

,State,License Type,Violation,Precinct,County,Issuing Agency,Violation Status
0,NY,PAS,CROSSWALK,44,BX,TRAFFIC,HEARING HELD-GUILTY
1,NY,COM,FAIL TO DSPLY MUNI METER RECPT,19,NY,TRAFFIC,HEARING HELD-GUILTY REDUCTION
2,NY,PAS,BIKE LANE,77,K,TRAFFIC,HEARING HELD-GUILTY
3,IN,PAS,BIKE LANE,14,NY,TRAFFIC,HEARING HELD-NOT GUILTY
4,NY,PAS,NO PARKING-STREET CLEANING,104,Q,TRAFFIC,HEARING PENDING

In [57]:
from sklearn.preprocessing import LabelEncoder

# one hot encoding
X_train = pd.get_dummies(df_train_new2.iloc[:, :-1])

# convert labels to integers
le = LabelEncoder()
y_train = le.fit_transform(df_train_new2['Violation Status'])

print(y_train)
X_train.head()

[ 8  9  8 ...,  9 10 10]

,Precinct,State_99,State_AB,State_AL,State_AR,State_AZ,State_BC,State_CA,State_CO,State_CT,...,Issuing Agency_HOUSING AUTHORITY,Issuing Agency_NYC TRANSIT AUTHORITY MANAGERS,Issuing Agency_NYS COURT OFFICERS,Issuing Agency_NYS PARKS POLICE,Issuing Agency_OTHER/UNKNOWN AGENCIES,Issuing Agency_PARKING CONTROL UNIT,Issuing Agency_PARKS DEPARTMENT,Issuing Agency_POLICE DEPARTMENT,Issuing Agency_TRAFFIC,Issuing Agency_TRANSIT AUTHORITY
0,44,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,77,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,104,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [61]:
df_test = pd.read_csv('./test.csv')
df_test_new = df_test[['State', 'License Type', 'Violation', 'Precinct', 'County', 'Issuing Agency']]
df_test_new.isnull().sum()

State                0
License Type         0
Violation           29
Precinct             0
County            1617
Issuing Agency      26
dtype: int64

In [66]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 18 columns):
ID                     200000 non-null int64
Plate                  200000 non-null object
State                  200000 non-null object
License Type           200000 non-null object
Summons Number         200000 non-null int64
Issue Date             200000 non-null object
Violation Time         199975 non-null object
Violation              199971 non-null object
Judgment Entry Date    22273 non-null object
Fine Amount            200000 non-null float64
Penalty Amount         200000 non-null float64
Interest Amount        200000 non-null float64
Reduction Amount       200000 non-null float64
Payment Amount         200000 non-null float64
Amount Due             200000 non-null float64
Precinct               200000 non-null float64
County                 198383 non-null object
Issuing Agency         199974 non-null object
dtypes: float64(7), int64(2), object(9)
memory usage: 27.5+ MB

In [78]:
for s in df_test['State'].unique():
    if s not in df_train['State'].unique():
        print(s)
        
print(len(df_train['State'].unique()))
print(len(df_test['State'].unique()))

GV
HI
AK
PE
WY
57
60

In [79]:
for lt in df_test['License Type'].unique():
    if lt not in df_train['License Type'].unique():
        print(lt)
        
print(len(df_train['License Type'].unique()))
print(len(df_test['License Type'].unique()))

SOS
NLM
FPW
THC
LMA
SUP
AMB
NYA
BOT
FAR
OMF
BOB
NYS
47
56

In [62]:
# one hot encoding
X_test = pd.get_dummies(df_test_new.iloc[:, :])
X_test.head()

,Precinct,State_99,State_AB,State_AK,State_AL,State_AR,State_AZ,State_CA,State_CO,State_CT,...,Issuing Agency_NYC TRANSIT AUTHORITY MANAGERS,Issuing Agency_NYS COURT OFFICERS,Issuing Agency_NYS PARKS POLICE,Issuing Agency_OTHER/UNKNOWN AGENCIES,Issuing Agency_PARKING CONTROL UNIT,Issuing Agency_PARKS DEPARTMENT,Issuing Agency_POLICE DEPARTMENT,Issuing Agency_PORT AUTHORITY,Issuing Agency_TRAFFIC,Issuing Agency_TRANSIT AUTHORITY
0,14.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,104.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,111.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,14.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,88.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
# 注意要改loop
X_train['State_GV'] = 0
X_train['State_HI'] = 0
X_train['State_AK'] = 0

X_train['License Type_SOS'] = 0

In [63]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_test = clf.predict(X_test)
print(y_test)

ValueError: Number of features of the model must match the input. Model n_features is 209 and input n_features is 228